packages:
  - website
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@iconify-json/lucide@1.2.122'
  - '@astrojs/internal-helpers@0.10.3'
  - '@astrojs/markdown-satteri@0.3.6'
  - '@biomejs/biome@2.5.9 || 2.5.13'
  - '@biomejs/cli-darwin-arm64@2.5.9 || 2.5.13'
  - '@biomejs/cli-darwin-x64@2.5.9 || 2.5.13'
  - '@biomejs/cli-linux-arm64-musl@2.5.9 || 2.5.13'
  - '@biomejs/cli-linux-arm64@2.5.9 || 2.5.13'
  - '@biomejs/cli-linux-x64-musl@2.5.9 || 2.5.13'
  - '@biomejs/cli-linux-x64@2.5.9 || 2.5.13'
  - '@biomejs/cli-win32-arm64@2.5.9 || 2.5.13'
  - '@biomejs/cli-win32-x64@2.5.9 || 2.5.13'
  - '@vitest/coverage-v8@5.0.0 || 5.0.1'
  - '@vitest/expect@5.0.0'
  - '@vitest/mocker@5.0.0 || 5.0.1'
  - '@vitest/pretty-format@5.0.0'
  - '@vitest/runner@5.0.0'
  - '@vitest/snapshot@5.0.0'
  - '@vitest/spy@5.0.0 || 5.0.1'
  - '@vitest/utils@5.0.0'
  - astro-icon@1.2.0
  - astro@7.2.3
  - marked@18.0.10
  - vitest@5.0.0 || 5.0.1
  - wrap-ansi@10.0.1
  - dependency-cruiser@18.3.1
