import type { InputAction } from './input-handler'

/**
 * The keymap is the single source of truth for normal-mode keyboard shortcuts.
 *
 * It drives four things that used to be maintained (and drift) separately:
 *   1. dispatch        — the input handler looks up the pressed key here
 *   2. the `?` overlay — rendered from {@link getHelpGroups}
 *   3. the footer hint — rendered from {@link getFooterHints}
 *   4. the README      — generated by {@link renderReadmeKeyTable}
 *
 * Add a binding once and all four stay correct.
 */

export type KeyGroup = 'Navigation' | 'Selection' | 'Filtering' | 'View'

/** Group display order for the help overlay and README. */
export const KEY_GROUPS: KeyGroup[] = ['Navigation', 'Selection', 'Filtering', 'View']

export interface KeyBinding {
  /**
   * readline `key.name` tokens that trigger {@link action}. Shifted letters are
   * normalized to uppercase tokens (see {@link findBinding}). Omit for keys the
   * input handler resolves specially (e.g. `/`, `!`, `?`, Enter, Esc).
   */
  tokens?: string[]
  /** Action dispatched when a token matches. Omit for display-only entries. */
  action?: InputAction
  /** How the key is shown in the help overlay and README, e.g. '↑ / k'. */
  displayKeys: string
  /** Full description shown in the help overlay and README. */
  help: string
  group: KeyGroup
  /** Short footer hint; omit to keep the key out of the compact footer line. */
  footer?: { keyLabel: string; label: string }
}

export const KEY_BINDINGS: KeyBinding[] = [
  // Navigation
  {
    tokens: ['up', 'k'],
    action: { type: 'navigate_up' },
    displayKeys: '↑ / k',
    help: 'Move up',
    group: 'Navigation',
    footer: { keyLabel: '↑/↓', label: 'Move' },
  },
  {
    tokens: ['down', 'j'],
    action: { type: 'navigate_down' },
    displayKeys: '↓ / j',
    help: 'Move down',
    group: 'Navigation',
  },
  {
    tokens: ['g'],
    action: { type: 'navigate_top' },
    displayKeys: 'g',
    help: 'Jump to the first package',
    group: 'Navigation',
  },
  {
    tokens: ['G'],
    action: { type: 'navigate_bottom' },
    displayKeys: 'G',
    help: 'Jump to the last package',
    group: 'Navigation',
  },

  // Selection
  {
    tokens: ['left'],
    action: { type: 'select_left' },
    displayKeys: '←',
    help: 'Cycle selection left (none → range → latest)',
    group: 'Selection',
    footer: { keyLabel: '←/→', label: 'Select' },
  },
  {
    tokens: ['right'],
    action: { type: 'select_right' },
    displayKeys: '→',
    help: 'Cycle selection right (none → range → latest)',
    group: 'Selection',
  },
  {
    tokens: ['space'],
    action: { type: 'toggle_selection' },
    displayKeys: 'Space',
    help: 'Toggle the current package on/off',
    group: 'Selection',
  },
  {
    tokens: ['m'],
    action: { type: 'bulk_select_minor' },
    displayKeys: 'm',
    help: 'Select all minor/patch updates',
    group: 'Selection',
    footer: { keyLabel: 'M', label: 'Minor' },
  },
  {
    tokens: ['l'],
    action: { type: 'bulk_select_latest' },
    displayKeys: 'l',
    help: 'Select all latest updates (including major)',
    group: 'Selection',
    footer: { keyLabel: 'L', label: 'All' },
  },
  {
    tokens: ['u'],
    action: { type: 'bulk_unselect_all' },
    displayKeys: 'u',
    help: 'Unselect all packages',
    group: 'Selection',
    footer: { keyLabel: 'U', label: 'None' },
  },
  {
    displayKeys: 'Enter',
    help: 'Confirm selection and upgrade',
    group: 'Selection',
  },

  // Filtering
  {
    displayKeys: '/',
    help: 'Search packages by name',
    group: 'Filtering',
    footer: { keyLabel: '/', label: 'Search' },
  },
  {
    tokens: ['d'],
    action: { type: 'toggle_dep_type_filter', depType: 'devDependencies' },
    displayKeys: 'd',
    help: 'Toggle devDependencies',
    group: 'Filtering',
    footer: { keyLabel: 'D/P/O', label: 'Filter' },
  },
  {
    tokens: ['p'],
    action: { type: 'toggle_dep_type_filter', depType: 'peerDependencies' },
    displayKeys: 'p',
    help: 'Toggle peerDependencies',
    group: 'Filtering',
  },
  {
    tokens: ['o'],
    action: { type: 'toggle_dep_type_filter', depType: 'optionalDependencies' },
    displayKeys: 'o',
    help: 'Toggle optionalDependencies',
    group: 'Filtering',
  },
  {
    tokens: ['s'],
    action: { type: 'trigger_audit_scan' },
    displayKeys: 's',
    help: 'Run the vulnerability audit',
    group: 'Filtering',
    footer: { keyLabel: 'S', label: 'Audit' },
  },
  {
    tokens: ['v'],
    action: { type: 'toggle_vulnerable_filter' },
    displayKeys: 'v',
    help: 'Show only vulnerable packages',
    group: 'Filtering',
  },
  {
    displayKeys: 'Esc',
    help: 'Clear the active search filter',
    group: 'Filtering',
  },

  // View
  {
    tokens: ['i'],
    action: { type: 'toggle_info_modal' },
    displayKeys: 'i',
    help: 'View package details and changelog',
    group: 'View',
    footer: { keyLabel: 'I', label: 'Info' },
  },
  {
    tokens: ['t'],
    action: { type: 'toggle_theme_modal' },
    displayKeys: 't',
    help: 'Change the color theme',
    group: 'View',
  },
  {
    displayKeys: '?',
    help: 'Show this help',
    group: 'View',
    footer: { keyLabel: '?', label: 'Help' },
  },
  {
    displayKeys: '!',
    help: 'Show the performance/debug panel',
    group: 'View',
  },
]

/**
 * Resolve a pressed key token to its binding. Tries an exact match first so the
 * case-sensitive vim pair `g`/`G` is honored, then falls back to the lowercase
 * letter so shifted letters (e.g. `M`) still trigger their lowercase binding.
 */
export function findBinding(token: string): KeyBinding | undefined {
  const exact = KEY_BINDINGS.find((binding) => binding.tokens?.includes(token))
  if (exact) return exact
  if (/^[A-Z]$/.test(token)) {
    const lower = token.toLowerCase()
    return KEY_BINDINGS.find((binding) => binding.tokens?.includes(lower))
  }
  return undefined
}

// Computed once at module load — KEY_BINDINGS is static so these never change.
const _footerHints: Array<{ keyLabel: string; label: string }> = KEY_BINDINGS.flatMap((binding) =>
  binding.footer ? [binding.footer] : []
)
const _helpGroups: Array<{ group: KeyGroup; bindings: KeyBinding[] }> = KEY_GROUPS.map((group) => ({
  group,
  bindings: KEY_BINDINGS.filter((b) => b.group === group),
})).filter((entry) => entry.bindings.length > 0)

/** Curated short hints for the compact footer line, in display order. */
export function getFooterHints(): Array<{ keyLabel: string; label: string }> {
  return _footerHints
}

/** Bindings grouped for the `?` help overlay, preserving {@link KEY_GROUPS} order. */
export function getHelpGroups(): Array<{ group: KeyGroup; bindings: KeyBinding[] }> {
  return _helpGroups
}

/**
 * Render the README "Keyboard Shortcuts" markdown table from the keymap. This is
 * the body placed between the `<!-- KEYS:START -->`/`<!-- KEYS:END -->` markers;
 * a test fails if the README drifts from it (see keymap-readme.test.ts).
 */
export function renderReadmeKeyTable(): string {
  const rows = KEY_BINDINGS.map((binding) => `| \`${binding.displayKeys}\` | ${binding.help} |`)
  return ['| Key | Action |', '|-----|--------|', ...rows].join('\n')
}
