import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  buildConfigTemplate,
  findExistingConfigFile,
  INIT_CONFIG_FILENAME,
} from '../../../../src/shared/config/init-config'
import { PACKAGE_VERSION } from '../../../../src/shared/config/package-meta'
import {
  type InupProjectConfig,
  loadProjectConfig,
} from '../../../../src/shared/config/project-config'

describe('buildConfigTemplate', () => {
  let testDir: string

  beforeEach(() => {
    testDir = join(tmpdir(), `inup-init-test-${process.pid}-${Math.random().toString(36).slice(2)}`)
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  it('produces a file the config loader parses without warnings', () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
    writeFileSync(join(testDir, INIT_CONFIG_FILENAME), buildConfigTemplate())

    const config = loadProjectConfig(testDir)

    // A parse failure would surface as a warning and an empty config; the
    // template's empty arrays/false booleans must round-trip instead.
    expect(warn).not.toHaveBeenCalled()
    expect(config.ignore).toEqual([])
    expect(config.exclude).toEqual([])
    expect(config.scanDirs).toEqual([])
    expect(config.showPeerDependencyVulnerabilities).toBe(false)
    expect(config.showOptionalDependencyVulnerabilities).toBe(false)
    // concurrency ships commented out — enabling it would pin parallelism.
    expect(config.concurrency).toBeUndefined()
    // native ships commented out — the core stays on by default.
    expect(config.native).toBeUndefined()
    warn.mockRestore()
  })

  it('documents every InupProjectConfig field', () => {
    // Compile-time sync check: adding a field to InupProjectConfig breaks this
    // Record until the list — and therefore the template — is updated too.
    const documentedFields: Record<keyof Required<InupProjectConfig>, true> = {
      ignore: true,
      exclude: true,
      scanDirs: true,
      showPeerDependencyVulnerabilities: true,
      showOptionalDependencyVulnerabilities: true,
      concurrency: true,
      native: true,
    }
    const template = buildConfigTemplate()
    for (const field of Object.keys(documentedFields)) {
      expect(template).toContain(`"${field}"`)
    }
  })

  describe('uncommenting optional fields', () => {
    // Every field the template ships commented out, and what it loads as once enabled.
    const OPTIONAL_FIELDS: Record<string, unknown> = {
      minimumReleaseAge: 10080,
      minimumReleaseAgeExclude: ['@myco/*'],
      concurrency: 4,
      native: false,
    }
    const COMMENTED_FIELD = /^(\s*)\/\/ ("(\w+)":.*)$/

    /** The template with `fields` enabled the way a user would: by deleting the `// `. */
    const uncomment = (fields: string[]) =>
      buildConfigTemplate()
        .split('\n')
        .map((line) => {
          const match = COMMENTED_FIELD.exec(line)
          return match && fields.includes(match[3]) ? match[1] + match[2] : line
        })
        .join('\n')

    const names = Object.keys(OPTIONAL_FIELDS)
    // Every non-empty subset: each field alone, every combination, and all of them together.
    const subsets = Array.from({ length: 2 ** names.length - 1 }, (_, i) => {
      const fields = names.filter((_, bit) => (i + 1) & (1 << bit))
      return { fields, label: fields.join(' + ') }
    })

    it('ships exactly these fields commented out', () => {
      const commented = buildConfigTemplate()
        .split('\n')
        .flatMap((line) => COMMENTED_FIELD.exec(line)?.[3] ?? [])
      expect(commented).toEqual(names)
    })

    it.each(subsets)('still parses with $label uncommented', ({ fields }) => {
      const warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
      writeFileSync(join(testDir, INIT_CONFIG_FILENAME), uncomment(fields))

      const config = loadProjectConfig(testDir) as Record<string, unknown>

      expect(warn).not.toHaveBeenCalled()
      for (const field of fields) expect(config[field]).toEqual(OPTIONAL_FIELDS[field])
      expect(config.showOptionalDependencyVulnerabilities).toBe(false)
      warn.mockRestore()
    })
  })

  it('stamps the generating inup version and the docs URL in the header', () => {
    const template = buildConfigTemplate()
    expect(template.startsWith(`// .inuprc — generated by inup v${PACKAGE_VERSION}`)).toBe(true)
    expect(template).toContain(
      'https://github.com/donfear/inup/blob/main/docs/guide/configuration.md'
    )
  })
})

describe('findExistingConfigFile', () => {
  let testDir: string

  beforeEach(() => {
    testDir = join(tmpdir(), `inup-find-test-${process.pid}-${Math.random().toString(36).slice(2)}`)
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  it('returns null when the directory has no config file', () => {
    expect(findExistingConfigFile(testDir)).toBeNull()
  })

  it.each(['.inuprc', '.inuprc.json', 'inup.config.json'])('finds %s', (filename) => {
    writeFileSync(join(testDir, filename), '{}')
    expect(findExistingConfigFile(testDir)).toBe(join(testDir, filename))
  })

  it('does not walk parent directories, unlike the loader', () => {
    const subDir = join(testDir, 'packages', 'app')
    mkdirSync(subDir, { recursive: true })
    writeFileSync(join(testDir, '.inuprc'), '{}')

    expect(findExistingConfigFile(subDir)).toBeNull()
  })
})
