import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  buildConfigTemplate,
  findExistingConfigFile,
  INIT_CONFIG_FILENAME,
} from '../../../../src/shared/config/init-config'
import { PACKAGE_VERSION } from '../../../../src/shared/config/package-meta'
import {
  type InupProjectConfig,
  loadProjectConfig,
} from '../../../../src/shared/config/project-config'

describe('buildConfigTemplate', () => {
  let testDir: string

  beforeEach(() => {
    testDir = join(tmpdir(), `inup-init-test-${process.pid}-${Math.random().toString(36).slice(2)}`)
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  it('produces a file the config loader parses without warnings', () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
    writeFileSync(join(testDir, INIT_CONFIG_FILENAME), buildConfigTemplate())

    const config = loadProjectConfig(testDir)

    // A parse failure would surface as a warning and an empty config; the
    // template's empty arrays/false booleans must round-trip instead.
    expect(warn).not.toHaveBeenCalled()
    expect(config.ignore).toEqual([])
    expect(config.exclude).toEqual([])
    expect(config.scanDirs).toEqual([])
    expect(config.showPeerDependencyVulnerabilities).toBe(false)
    expect(config.showOptionalDependencyVulnerabilities).toBe(false)
    // concurrency ships commented out — enabling it would pin parallelism.
    expect(config.concurrency).toBeUndefined()
    warn.mockRestore()
  })

  it('documents every InupProjectConfig field', () => {
    // Compile-time sync check: adding a field to InupProjectConfig breaks this
    // Record until the list — and therefore the template — is updated too.
    const documentedFields: Record<keyof Required<InupProjectConfig>, true> = {
      ignore: true,
      exclude: true,
      scanDirs: true,
      showPeerDependencyVulnerabilities: true,
      showOptionalDependencyVulnerabilities: true,
      concurrency: true,
    }
    const template = buildConfigTemplate()
    for (const field of Object.keys(documentedFields)) {
      expect(template).toContain(`"${field}"`)
    }
  })

  it('stamps the generating inup version and the docs URL in the header', () => {
    const template = buildConfigTemplate()
    expect(template.startsWith(`// .inuprc — generated by inup v${PACKAGE_VERSION}`)).toBe(true)
    expect(template).toContain('https://donfear.github.io/inup/docs/configuration/')
  })
})

describe('findExistingConfigFile', () => {
  let testDir: string

  beforeEach(() => {
    testDir = join(tmpdir(), `inup-find-test-${process.pid}-${Math.random().toString(36).slice(2)}`)
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  it('returns null when the directory has no config file', () => {
    expect(findExistingConfigFile(testDir)).toBeNull()
  })

  it.each(['.inuprc', '.inuprc.json', 'inup.config.json'])('finds %s', (filename) => {
    writeFileSync(join(testDir, filename), '{}')
    expect(findExistingConfigFile(testDir)).toBe(join(testDir, filename))
  })

  it('does not walk parent directories, unlike the loader', () => {
    const subDir = join(testDir, 'packages', 'app')
    mkdirSync(subDir, { recursive: true })
    writeFileSync(join(testDir, '.inuprc'), '{}')

    expect(findExistingConfigFile(subDir)).toBeNull()
  })
})
