import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  isPackageIgnored,
  loadProjectConfig,
  stripJsonComments,
  stripTrailingCommas,
} from '../../../../src/shared/config/project-config'

describe('project-config', () => {
  let testDir: string

  beforeEach(() => {
    testDir = join(tmpdir(), `inup-test-${Date.now()}`)
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  describe('loadProjectConfig()', () => {
    it('should return empty config when no config file exists', () => {
      const config = loadProjectConfig(testDir)
      expect(config).toEqual({})
    })

    it('should load config from .inuprc', () => {
      const configContent = {
        ignore: ['lodash', 'moment'],
      }
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify(configContent))

      const config = loadProjectConfig(testDir)
      expect(config.ignore).toEqual(['lodash', 'moment'])
    })

    it('drops a non-array ignore field', () => {
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ ignore: 'react' }))

      const config = loadProjectConfig(testDir)
      expect(config.ignore).toBeUndefined()
    })

    it('should load config from .inuprc.json', () => {
      const configContent = {
        ignore: ['react', 'react-dom'],
      }
      writeFileSync(join(testDir, '.inuprc.json'), JSON.stringify(configContent))

      const config = loadProjectConfig(testDir)
      expect(config.ignore).toEqual(['react', 'react-dom'])
    })

    it('should load config from inup.config.json', () => {
      const configContent = {
        ignore: ['typescript'],
        exclude: ['dist', 'node_modules'],
      }
      writeFileSync(join(testDir, 'inup.config.json'), JSON.stringify(configContent))

      const config = loadProjectConfig(testDir)
      expect(config.ignore).toEqual(['typescript'])
      expect(config.exclude).toEqual(['dist', 'node_modules'])
    })

    it('should prefer .inuprc over other config files', () => {
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ ignore: ['from-inuprc'] }))
      writeFileSync(join(testDir, '.inuprc.json'), JSON.stringify({ ignore: ['from-inuprc-json'] }))
      writeFileSync(
        join(testDir, 'inup.config.json'),
        JSON.stringify({ ignore: ['from-inup-config'] })
      )

      const config = loadProjectConfig(testDir)
      expect(config.ignore).toEqual(['from-inuprc'])
    })

    it('should search parent directories for config', () => {
      const subDir = join(testDir, 'packages', 'my-package')
      mkdirSync(subDir, { recursive: true })

      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ ignore: ['parent-config'] }))

      const config = loadProjectConfig(subDir)
      expect(config.ignore).toEqual(['parent-config'])
    })

    it('parses a config containing line and block comments', () => {
      writeFileSync(
        join(testDir, '.inuprc'),
        [
          '// .inuprc — generated by inup v1.0.0',
          '{',
          '  // packages to skip',
          '  "ignore": ["lodash"], /* inline note */',
          '  "exclude": ["dist"]',
          '  // "concurrency": 4',
          '}',
        ].join('\n')
      )

      const config = loadProjectConfig(testDir)
      expect(config.ignore).toEqual(['lodash'])
      expect(config.exclude).toEqual(['dist'])
      expect(config.concurrency).toBeUndefined()
    })

    it('accepts trailing commas', () => {
      writeFileSync(
        join(testDir, '.inuprc'),
        '{\n  "ignore": ["a", "b",],\n  "concurrency": 4, // pinned\n}'
      )

      expect(loadProjectConfig(testDir)).toEqual({ ignore: ['a', 'b'], concurrency: 4 })
    })

    it('refuses invalid JSON, naming the file and the position', () => {
      const configPath = join(testDir, '.inuprc')
      const content =
        '// header\n{\n  "ignore": [], /* note */\n  "exclude": []\n  "scanDirs": []\n}'
      writeFileSync(configPath, content)

      expect(() => loadProjectConfig(testDir)).toThrow(`Invalid config file ${configPath}: `)
      // Stripping blanks rather than deletes, so the position points into the file as written.
      const position = content.indexOf('"scanDirs"')
      expect(() => loadProjectConfig(testDir)).toThrow(new RegExp(`at position ${position}\\b`))
    })

    it('never falls back to a parent config when the nearest one is broken', () => {
      // The broken file may be the one turning the cooldown on; quietly running
      // with the parent's settings instead would leave the user unprotected.
      const child = join(testDir, 'child')
      mkdirSync(child)
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ ignore: ['from-parent'] }))
      writeFileSync(join(child, '.inuprc'), '{ "minimumReleaseAge": 10080 "ignore": [] }')

      expect(() => loadProjectConfig(child)).toThrow(join(child, '.inuprc'))
    })

    it('never falls back to a lower-precedence file in the same directory', () => {
      writeFileSync(join(testDir, '.inuprc'), 'not valid json {')
      writeFileSync(join(testDir, '.inuprc.json'), JSON.stringify({ ignore: ['from-json'] }))

      expect(() => loadProjectConfig(testDir)).toThrow(join(testDir, '.inuprc'))
    })

    it.each(['null', '[]', '42'])('refuses a top-level %s instead of an object', (raw) => {
      writeFileSync(join(testDir, '.inuprc'), raw)

      expect(() => loadProjectConfig(testDir)).toThrow('expected a JSON object')
    })

    it('should filter out non-string values in ignore array', () => {
      const configContent = {
        ignore: ['valid', 123, 'also-valid', null, 'still-valid'],
      }
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify(configContent))

      const config = loadProjectConfig(testDir)
      expect(config.ignore).toEqual(['valid', 'also-valid', 'still-valid'])
    })

    it('should load ignoreMajor patterns', () => {
      writeFileSync(
        join(testDir, '.inuprc'),
        JSON.stringify({ ignoreMajor: ['@tiptap/*', 'react'] })
      )

      const config = loadProjectConfig(testDir)
      expect(config.ignoreMajor).toEqual(['@tiptap/*', 'react'])
    })

    it('drops a non-array ignoreMajor field and filters non-string entries', () => {
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ ignoreMajor: '@tiptap/*' }))
      expect(loadProjectConfig(testDir).ignoreMajor).toBeUndefined()

      writeFileSync(
        join(testDir, '.inuprc'),
        JSON.stringify({ ignoreMajor: ['@tiptap/*', 42, null] })
      )
      expect(loadProjectConfig(testDir).ignoreMajor).toEqual(['@tiptap/*'])
    })

    it('should load showPeerDependencyVulnerabilities when set to a boolean', () => {
      writeFileSync(
        join(testDir, '.inuprc'),
        JSON.stringify({ showPeerDependencyVulnerabilities: true })
      )

      const config = loadProjectConfig(testDir)
      expect(config.showPeerDependencyVulnerabilities).toBe(true)
    })

    it('should load showOptionalDependencyVulnerabilities when set to a boolean', () => {
      writeFileSync(
        join(testDir, '.inuprc'),
        JSON.stringify({ showOptionalDependencyVulnerabilities: true })
      )

      const config = loadProjectConfig(testDir)
      expect(config.showOptionalDependencyVulnerabilities).toBe(true)
    })

    it('loads minimumReleaseAge and its exclusion list', () => {
      writeFileSync(
        join(testDir, '.inuprc'),
        JSON.stringify({
          minimumReleaseAge: 10080,
          minimumReleaseAgeExclude: ['@myco/*', 42, 'internal-tool', null],
        })
      )

      const config = loadProjectConfig(testDir)
      expect(config.minimumReleaseAge).toBe(10080)
      // Non-string entries are filtered, like the ignore list.
      expect(config.minimumReleaseAgeExclude).toEqual(['@myco/*', 'internal-tool'])
    })

    it('accepts minimumReleaseAge of 0 (explicitly disabled)', () => {
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ minimumReleaseAge: 0 }))

      expect(loadProjectConfig(testDir).minimumReleaseAge).toBe(0)
    })

    it('drops invalid minimumReleaseAge values', () => {
      for (const bad of [-5, '10080', null]) {
        writeFileSync(join(testDir, '.inuprc'), `{"minimumReleaseAge": ${JSON.stringify(bad)}}`)
        expect(loadProjectConfig(testDir).minimumReleaseAge).toBeUndefined()
      }
    })

    it('drops a non-array minimumReleaseAgeExclude', () => {
      writeFileSync(
        join(testDir, '.inuprc'),
        JSON.stringify({ minimumReleaseAgeExclude: 'not-an-array' })
      )

      expect(loadProjectConfig(testDir).minimumReleaseAgeExclude).toBeUndefined()
    })
  })

  describe('native field', () => {
    it.each([true, false])('loads native: %s', (native) => {
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ native }))
      expect(loadProjectConfig(testDir).native).toBe(native)
    })

    it.each(['yes', 1, null])('ignores a non-boolean native value (%s)', (native) => {
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ native }))
      expect(loadProjectConfig(testDir).native).toBeUndefined()
    })
  })

  describe('concurrency field', () => {
    it('accepts an integer concurrency within the pool range', () => {
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ concurrency: 8 }))
      expect(loadProjectConfig(testDir).concurrency).toBe(8)
    })

    it.each([
      ['"8"', '"8"'],
      ['zero', '0'],
      ['negative', '-3'],
      ['above pool', '99'],
      ['fractional', '7.5'],
    ])('drops an invalid concurrency value (%s) and says so', (_label, raw) => {
      // Silent dropping would invert the user's intent: they pinned a low limit
      // to protect a slow/metered link, and the run would adapt up to 24.
      const warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
      writeFileSync(join(testDir, '.inuprc'), `{"concurrency": ${raw}}`)
      expect(loadProjectConfig(testDir).concurrency).toBeUndefined()
      expect(warn).toHaveBeenCalledWith(expect.stringContaining('concurrency'))
      warn.mockRestore()
    })

    it('does not warn when concurrency is valid or absent', () => {
      const warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ concurrency: 8 }))
      loadProjectConfig(testDir)
      writeFileSync(join(testDir, '.inuprc'), JSON.stringify({ ignore: [] }))
      loadProjectConfig(testDir)
      expect(warn).not.toHaveBeenCalled()
      warn.mockRestore()
    })
  })

  describe('unknown keys', () => {
    let warn: ReturnType<typeof vi.spyOn>

    beforeEach(() => {
      warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
    })

    afterEach(() => {
      warn.mockRestore()
    })

    it.each([
      ['minimumReleaseAg', 'minimumReleaseAge'],
      ['minimum-release-age', 'minimumReleaseAge'],
      ['concurency', 'concurrency'],
      ['Native', 'native'],
    ])('warns about "%s", naming the file and suggesting "%s"', (key, suggestion) => {
      // A typo'd key must not read as "setting not configured" without a word.
      const configPath = join(testDir, '.inuprc')
      writeFileSync(configPath, JSON.stringify({ [key]: 1, ignore: ['kept'] }))

      expect(loadProjectConfig(testDir)).toEqual({ ignore: ['kept'] })
      expect(warn).toHaveBeenCalledExactlyOnceWith(
        `Warning: ignoring unknown key "${key}" in ${configPath} (did you mean "${suggestion}"?)`
      )
    })

    it('warns without a suggestion when no known key is close', () => {
      const configPath = join(testDir, '.inuprc')
      writeFileSync(configPath, JSON.stringify({ theme: 'dark' }))

      loadProjectConfig(testDir)
      expect(warn).toHaveBeenCalledExactlyOnceWith(
        `Warning: ignoring unknown key "theme" in ${configPath}`
      )
    })
  })

  describe('isPackageIgnored()', () => {
    it('should match exact package names', () => {
      expect(isPackageIgnored('lodash', ['lodash'])).toBe(true)
      expect(isPackageIgnored('lodash', ['moment'])).toBe(false)
    })

    it('should match wildcard patterns with *', () => {
      expect(isPackageIgnored('@babel/core', ['@babel/*'])).toBe(true)
      expect(isPackageIgnored('@babel/preset-env', ['@babel/*'])).toBe(true)
      expect(isPackageIgnored('@types/node', ['@babel/*'])).toBe(false)
    })

    it('should match prefix patterns', () => {
      expect(isPackageIgnored('eslint-plugin-react', ['eslint-*'])).toBe(true)
      expect(isPackageIgnored('eslint-config-prettier', ['eslint-*'])).toBe(true)
      expect(isPackageIgnored('prettier', ['eslint-*'])).toBe(false)
    })

    it('should match suffix patterns', () => {
      expect(isPackageIgnored('react-dom', ['*-dom'])).toBe(true)
      expect(isPackageIgnored('preact-dom', ['*-dom'])).toBe(true)
      expect(isPackageIgnored('react', ['*-dom'])).toBe(false)
    })

    it('should match single character wildcard with ?', () => {
      expect(isPackageIgnored('lodash', ['lodas?'])).toBe(true)
      expect(isPackageIgnored('lodash', ['lod???'])).toBe(true)
      expect(isPackageIgnored('lodash', ['lod??'])).toBe(false)
    })

    it('should match multiple patterns', () => {
      const patterns = ['lodash', '@babel/*', 'eslint-*']
      expect(isPackageIgnored('lodash', patterns)).toBe(true)
      expect(isPackageIgnored('@babel/core', patterns)).toBe(true)
      expect(isPackageIgnored('eslint-plugin-react', patterns)).toBe(true)
      expect(isPackageIgnored('react', patterns)).toBe(false)
    })

    it('should return false for empty patterns array', () => {
      expect(isPackageIgnored('lodash', [])).toBe(false)
    })

    it('should handle scoped packages correctly', () => {
      expect(isPackageIgnored('@types/node', ['@types/*'])).toBe(true)
      expect(isPackageIgnored('@types/react', ['@types/react'])).toBe(true)
      expect(isPackageIgnored('@types/react-dom', ['@types/react'])).toBe(false)
      expect(isPackageIgnored('@types/react-dom', ['@types/react*'])).toBe(true)
    })

    it('should escape special regex characters in patterns', () => {
      // The dot in package names should be treated literally
      expect(isPackageIgnored('socket.io', ['socket.io'])).toBe(true)
      expect(isPackageIgnored('socketXio', ['socket.io'])).toBe(false)
    })
  })
})

describe('stripJsonComments()', () => {
  it('strips line comments to end of line', () => {
    expect(JSON.parse(stripJsonComments('{"a": 1 // note\n}'))).toEqual({ a: 1 })
  })

  it('strips block comments, including multi-line ones', () => {
    expect(JSON.parse(stripJsonComments('{/* x */"a": /* y\nz */ 1}'))).toEqual({ a: 1 })
  })

  it('leaves comment-like sequences inside strings untouched', () => {
    const input = '{"url": "https://example.com/path", "glob": "a/*"}'
    expect(JSON.parse(stripJsonComments(input))).toEqual({
      url: 'https://example.com/path',
      glob: 'a/*',
    })
  })

  it('handles escaped quotes inside strings', () => {
    expect(JSON.parse(stripJsonComments('{"a": "say \\"hi\\" // not a comment"}'))).toEqual({
      a: 'say "hi" // not a comment',
    })
  })

  it('does not crash on a truncated file ending in a string escape', () => {
    // Malformed input (unterminated string, dangling backslash at EOF): the
    // stripper must pass it through untouched and let JSON.parse report it.
    expect(stripJsonComments('{"a": "b\\')).toBe('{"a": "b\\')
  })

  it('preserves line numbers by blanking instead of deleting', () => {
    const stripped = stripJsonComments('// one\n// two\n{}')
    expect(stripped.split('\n')).toHaveLength(3)
    expect(JSON.parse(stripped)).toEqual({})
  })
})

describe('stripTrailingCommas()', () => {
  it('blanks commas that close an object or array, across whitespace and newlines', () => {
    expect(stripTrailingCommas('{"a": [1, 2,\n],\n}')).toBe('{"a": [1, 2 \n] \n}')
  })

  it('leaves commas inside strings untouched, including after escaped quotes', () => {
    const input = '{"a": ", }", "b": "\\", ]"}'
    expect(stripTrailingCommas(input)).toBe(input)
  })

  it('does not crash on a truncated file ending in a string escape', () => {
    expect(stripTrailingCommas('{"a": "b\\')).toBe('{"a": "b\\')
  })
})

describe('config normalization of list fields', () => {
  let testDir: string

  beforeEach(() => {
    testDir = join(tmpdir(), `inup-test-normalize-${Date.now()}`)
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
  })

  it('keeps only string entries in exclude and scanDirs', () => {
    writeFileSync(
      join(testDir, '.inuprc'),
      JSON.stringify({
        exclude: ['dist', 42, null, 'coverage'],
        scanDirs: ['packages', false, 'apps'],
      })
    )

    const config = loadProjectConfig(testDir)

    expect(config.exclude).toEqual(['dist', 'coverage'])
    expect(config.scanDirs).toEqual(['packages', 'apps'])
  })

  it('drops non-array exclude and scanDirs values', () => {
    writeFileSync(
      join(testDir, '.inuprc'),
      JSON.stringify({ exclude: 'dist', scanDirs: { nope: true } })
    )

    const config = loadProjectConfig(testDir)

    expect(config.exclude).toBeUndefined()
    expect(config.scanDirs).toBeUndefined()
  })
})
