import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { PACKAGE_NAME, PACKAGE_VERSION } from './package-meta'

/** The file `--init` writes; first in the loader's lookup order, so it always wins. */
export const INIT_CONFIG_FILENAME = `.${PACKAGE_NAME}rc`

const CONFIG_FILES = [
  `.${PACKAGE_NAME}rc`,
  `.${PACKAGE_NAME}rc.json`,
  `${PACKAGE_NAME}.config.json`,
]

/**
 * The config file already present in this directory, or null. Deliberately
 * does NOT walk parent directories like the loader does: `--init` creates a
 * project-local config, and a config higher up is no reason to block that.
 */
export function findExistingConfigFile(cwd: string): string | null {
  for (const configFile of CONFIG_FILES) {
    const configPath = join(cwd, configFile)
    if (existsSync(configPath)) {
      return configPath
    }
  }
  return null
}

/**
 * A fully commented starter config documenting every supported field.
 * Comments are legal here — the loader strips them before JSON.parse.
 */
export function buildConfigTemplate(): string {
  return `// .${PACKAGE_NAME}rc — generated by ${PACKAGE_NAME} v${PACKAGE_VERSION}
// Docs: https://donfear.github.io/${PACKAGE_NAME}/docs/configuration/
// Comments are allowed in this file; every field is optional.
{
  // Hide packages from upgrade checks entirely.
  // Exact names or globs: "lodash", "@babel/*", "eslint-*" (? matches one char).
  "ignore": [],

  // Suppress only MAJOR updates for these packages — minor/patch bumps still
  // show, and a package whose only update is a new major counts as up to date.
  // Same pattern syntax as "ignore".
  "ignoreMajor": [],

  // Skip directories while discovering package.json files (regex patterns).
  "exclude": [],

  // Scan these directory names even though they are on the default skip list
  // (node_modules, dist, build, coverage, out, lib, es, esm, cjs).
  "scanDirs": [],

  // Show vulnerability badges for peerDependencies / optionalDependencies.
  // Both default to false so that risk stays hidden unless you opt in.
  "showPeerDependencyVulnerabilities": false,
  "showOptionalDependencyVulnerabilities": false

  // Pin registry-fetch parallelism (integer 1-24) and disable adaptive
  // ramping — an escape hatch for slow or metered connections.
  // "concurrency": 4
}
`
}
