// Assemble and publish the per-platform native core packages for this inup
// version, from the addons the native-build workflow produced, and pin their
// hashes into inup.
//
//   node scripts/publish-native.mjs --artifacts <dir> [--out <dir>] [--dry-run]
//   node scripts/publish-native.mjs --check-pins
//
// - Refuses to publish anything unless every platform's addon is present.
// - Skips versions already on the registry, so a failed publish job can simply
//   be re-run.
// - Prereleases (1.8.0-rc.0) go to the `next` dist-tag, releases to `latest`.
// - Writes the sha512 of every platform's addon to PIN_FILE. inup downloads and
//   loads only the addons pinned there, so build inup after this. For a version
//   already on the registry it pins the published addon, which is what users
//   will download, rather than this run's build of it.
// - --check-pins fails unless the built dist/ pins an addon for every platform.
// Needs `pnpm build` first: package names come from the built loader.
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import {
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'
import { gunzipSync } from 'node:zlib'

/** napi-rs platform suffixes of every published addon. */
export const TARGET_ABIS = [
  'darwin-arm64',
  'darwin-x64',
  'linux-arm64-gnu',
  'linux-arm64-musl',
  'linux-x64-gnu',
  'linux-x64-musl',
  'win32-arm64-msvc',
  'win32-x64-msvc',
]

/** Source file of the pinned hashes; empty in the repository. */
export const PIN_FILE = 'src/shared/registry/native-integrity.ts'

/** SRI sha512 of an addon: the form inup compares downloads and its cache against. */
export function integrityOf(data) {
  return `sha512-${createHash('sha512').update(data).digest('base64')}`
}

/** native-integrity.ts pinning `pins` (`{ [abi]: integrity }`). */
export function pinSource(pins) {
  const entries = Object.keys(pins)
    .sort()
    .map((abi) => `  ${JSON.stringify(abi)}: ${JSON.stringify(pins[abi])},`)
  return [
    '// Generated by scripts/publish-native.mjs from the native cores released',
    '// with this version of inup. The checked-in file pins nothing.',
    'export const NATIVE_INTEGRITY: Readonly<Partial<Record<string, string>>> = {',
    ...entries,
    '}',
    '',
  ].join('\n')
}

/** Targets without a well-formed sha512 pin in `pins`. */
export function unpinned(pins, abis = TARGET_ABIS) {
  return abis.filter((abi) => !/^sha512-[A-Za-z0-9+/]{86}==$/.test(pins?.[abi] ?? ''))
}

export function distTagFor(version) {
  return version.includes('-') ? 'next' : 'latest'
}

/** npm `os` / `cpu` / `libc` constraints for a platform suffix. */
export function platformOf(abi) {
  const [os, cpu, variant] = abi.split('-')
  const platform = { os: [os], cpu: [cpu] }
  if (variant === 'gnu') platform.libc = ['glibc']
  if (variant === 'musl') platform.libc = ['musl']
  return platform
}

export function platformManifest({ abi, version, name, repository }) {
  const file = `inup.${abi}.node`
  return {
    name,
    version,
    description: `inup's native core for ${abi}. Downloaded by \`inup --native\`; do not depend on it directly.`,
    license: 'MIT',
    repository,
    ...platformOf(abi),
    main: file,
    files: [file],
  }
}

/** Map each target to its addon file among `paths`; report the missing ones. */
export function findAddons(paths, abis = TARGET_ABIS) {
  const byName = new Map(paths.map((path) => [basename(path), path]))
  const found = new Map()
  const missing = []
  for (const abi of abis) {
    const path = byName.get(`inup.${abi}.node`)
    if (path) found.set(abi, path)
    else missing.push(abi)
  }
  return { found, missing }
}

function listFiles(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry)
    return statSync(path).isDirectory() ? listFiles(path) : [path]
  })
}

function isPublished(name, version) {
  try {
    execFileSync('npm', ['view', `${name}@${version}`, 'version'], { stdio: 'pipe' })
    return true
  } catch {
    return false
  }
}

/** The addon inside the published `name@version`, as users download it. */
function publishedAddon(name, version, abi, extractTarEntry) {
  const dir = mkdtempSync(join(tmpdir(), 'inup-native-'))
  try {
    const packed = execFileSync(
      'npm',
      ['pack', `${name}@${version}`, '--json', '--pack-destination', dir],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] }
    )
    const [{ filename }] = JSON.parse(packed)
    const tar = gunzipSync(readFileSync(join(dir, filename)))
    const addon = extractTarEntry(tar, `package/inup.${abi}.node`)
    if (!addon) throw new Error(`${name}@${version} has no inup.${abi}.node`)
    return addon
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

/** Fails unless the built inup pins an addon for every platform. */
async function checkPins() {
  const { NATIVE_INTEGRITY } = await import(resolve('dist/shared/registry/native-integrity.js'))
  const missing = unpinned(NATIVE_INTEGRITY)
  if (missing.length > 0) {
    const list = missing.join(', ')
    throw new Error(`dist/ pins no native core for: ${list}; run this script, then pnpm build`)
  }
  console.log(`dist/ pins the native core for all ${TARGET_ABIS.length} platforms`)
}

async function main() {
  const { values } = parseArgs({
    options: {
      artifacts: { type: 'string' },
      out: { type: 'string', default: 'native/npm' },
      'dry-run': { type: 'boolean', default: false },
      'check-pins': { type: 'boolean', default: false },
    },
  })
  if (values['check-pins']) return checkPins()
  if (!values.artifacts) throw new Error('--artifacts <dir> is required')

  const root = JSON.parse(readFileSync('package.json', 'utf8'))
  const { nativePackageName, extractTarEntry } = await import(
    resolve('dist/shared/registry/native-download.js')
  )

  const { found, missing } = findAddons(listFiles(resolve(values.artifacts)))
  if (missing.length > 0) {
    throw new Error(`refusing to publish, addons missing for: ${missing.join(', ')}`)
  }

  const out = resolve(values.out)
  rmSync(out, { recursive: true, force: true })
  const tag = distTagFor(root.version)
  const pins = {}
  for (const [abi, addon] of found) {
    const name = nativePackageName(abi)
    const dir = join(out, abi)
    mkdirSync(dir, { recursive: true })
    copyFileSync(addon, join(dir, `inup.${abi}.node`))
    const manifest = platformManifest({ abi, version: root.version, name, repository: root.repository })
    writeFileSync(join(dir, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`)

    // Checked in dry runs too: npm refuses even a dry-run publish of an existing
    // version, and CI dry-runs every push to main, including the release commit.
    const built = integrityOf(readFileSync(addon))
    if (isPublished(name, root.version)) {
      console.log(`skip ${name}@${root.version} (already published)`)
      pins[abi] = integrityOf(publishedAddon(name, root.version, abi, extractTarEntry))
      if (pins[abi] !== built) console.log(`  pinning the published ${name} addon, not this build's`)
      continue
    }
    pins[abi] = built
    const args = ['publish', dir, '--access', 'public', '--tag', tag]
    if (values['dry-run']) args.push('--dry-run')
    else args.push('--provenance')
    console.log(`npm ${args.join(' ')}`)
    execFileSync('npm', args, { stdio: 'inherit' })
  }

  writeFileSync(PIN_FILE, pinSource(pins))
  console.log(`pinned ${Object.keys(pins).length} native cores in ${PIN_FILE}; build inup next`)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error.message)
    process.exit(1)
  })
}
